// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID         string         `json:"id"`
	Email      string         `json:"email"`
	Status     string         `json:"status"`
	CreatedAt  string         `json:"createdAt"`
	ModifiedAt string         `json:"modifiedAt"`
	Contact    *UserContact   `json:"contact,omitempty"`
	Addresses  []*UserAddress `json:"addresses,omitempty"`
}

type UserAddress struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Prefix         *string `json:"prefix,omitempty"`
	StreetAddress1 string  `json:"streetAddress1"`
	StreetAddress2 *string `json:"streetAddress2,omitempty"`
	City           string  `json:"city"`
	State          string  `json:"state"`
	ZipCode        string  `json:"zipCode"`
	UserID         string  `json:"userId"`
}

type UserContact struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Phone     string `json:"phone"`
	UserID    string `json:"userId"`
}
